### ISSUE TITLE
Choose a licence

### ISSUE THREAD

**Issue by RiboRings** [moeinkh88/FDE_Solver#6]
The default licence when you create a template package is MIT, but we can also go for another one. For now, the licence is stored in [this file](https://github.com/moeinkh88/FDE_Solver/blob/build_package/LICENSE).

**Comment by moeinkh88** [comment]
> The default licence when you create a template package is MIT, but we can also go for another one. For now, the licence is stored in [this file](https://github.com/moeinkh88/FDE_Solver/blob/build_package/LICENSE).

Yes it is nice!
