### ISSUE TITLE
Make Travis CI and codecov work

### ISSUE THREAD

**Issue by RiboRings** [moeinkh88/FDE_Solver#7]
[Travis CI](https://www.travis-ci.com/) enables continuous integration of a GitHub repository and [codecov](https://about.codecov.io/) check that the code is tested to avoid errors and exceptions. They are free for public repositories, so we can set them up after we decide to make our repo public. They can also be run on shared repositories belonging to an organisation / team.

**Comment by moeinkh88** [comment]
OK do it, please.
